movie part initial css
lama-org/semi-front pull request #12
Opened 2021-09-07 14:32 UTC by itsChrisJang

movie part initial css
영화 부분 초기 css입니다.

2021-09-07 14:34 UTC, dntjr031 commented
브런치가 제가 만들었다 지운 브런치네여? ㅋㅋㅋㅋ

2021-09-08 00:09 UTC, itsChrisJang commented
> 브런치가 제가 만들었다 지운 브런치네여? ㅋㅋㅋㅋ
ㅋㅋㅋㅋㅋㅋㅋㅋ 그전에 받은곳이 그쪽이라 괜히 브런치 change 잘못했다가 날라갈거같아서 현재 브런치에서 develop으로 올렸어요 ㅋㅋㅋㅋㅋㅋ

2021-09-08 01:41 UTC, develjsh commented
오늘 집에 가서 확인해보겠습니다~

2021-09-08 13:03 UTC, dntjr031 requested changes
고생 많으셨습니다. 이부분만 고치면 병합해도 될것 같습니다.

자세한 스타일링은 추후 병합후에 진행하시는게 좋을 것 같습니다!

2021-09-08 13:03 UTC, dntjr031 commented on public/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&display=swap" rel="stylesheet" />
prettier 미적용되어있습니다.

2021-09-08 13:03 UTC, dntjr031 commented on src/components/AddFavourite.tsx
> +        <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z" />
`fill-rule`을 react형식에 맞춰 `fillRule` 으로 사용하기를 권장합니다.

2021-09-08 13:03 UTC, dntjr031 commented on src/screens/Movie.tsx
> +`;
미사용된 요소입니다. 사용을 하거나 삭제바랍니다

2021-09-08 13:03 UTC, dntjr031 commented on src/screens/Movie.tsx
> +  margin: 20px 0px;
0인경우 단위를 쓰지 않는것을 권장합니다.
0px => 0

2021-09-08 13:03 UTC, dntjr031 commented on src/screens/Movie.tsx
> +                          <StarIconImg src={starImg}></StarIconImg>
하위 엘리먼트 및 요소가 없을 시 Empty Tag를 사용하기를 권장합니다.
`<StarIconImg src={starImg} />`

2021-09-08 13:03 UTC, dntjr031 commented on src/screens/Movie.tsx
> +  }
쿼리문 작성시 쿼리 네임이 중복되면 안됩니다.
MovieQuery 라는 쿼리 네임은 Example에서 사용중이기 때문에 타입 생성시 에러가 발생하니 변경 하셔야 합니다

2021-09-09 15:33 UTC, itsChrisJang commented
수정하여 올렸습니다.
확인부탁드려요!!

2021-09-09 15:35 UTC, develjsh approved these changes
확인했습니다!

2021-09-10 13:06 UTC, dntjr031 approved these changes

2021-09-10 13:07 UTC, merged