프론트 수정요청 진행
lama-org/semi-front pull request #14
Opened 2021-09-25 08:01 UTC by itsChrisJang

1. 좌측 즐겨찾기 부분에 타이틀 제거
=> (제거 완료)
2. 원 사이즈 축소 (마우스 오버시 확대)
- 포스터 부분 스타일 조정
=> (완료) 높이 동일 하게 수정
- 애드 투 페이버릿 포스터 내부 하단으로 이동
=> 아직까지 살짝 밀리는 데 어떻게 해결해야할까용 ㅠㅠ?
- 별점도 포스터 내부 좌측 상단으로 이동
=> (완료)
- 마우스 오버시 포스터가 불투명 해지면서 제목 우측 상단에 표시되도록 변경
=> (완료)
3. 포스터 크기 더 줄여서 한 행에 5개 표시 
=> ( 5개 표시되도록 완료)

2021-09-25 12:50 UTC, itsChrisJang commented
Asignee 동율이형 추가 안되네용

2021-09-26 02:24 UTC, JAEMIN-LEE-ANDREW commented
왜인지는 모르겠지만 일단 키면 애러나고 애러 제거했는데 뭐가 보이지 않음.....

2021-09-26 08:25 UTC, itsChrisJang commented
그 전 커밋에서 tsx css만 수정된거라...
흠 .. 에러...

2021-09-26 12:22 UTC, dntjr031 commented
@itsChrisJang 
#15 각종 에러난 부분 수정해서 머지 요청했으니 확인 부탁드립니다.
머지 되는데로 여러 부분들 리뷰하겠습니다!

2021-09-27 08:27 UTC, itsChrisJang commented
네. 확인하겠습니다.
감사합니다.

2021-09-27 14:42 UTC, develjsh submitted a review, later dismissed
확인했습니다

2021-09-28 12:31 UTC, dntjr031 requested changes
# 포스터

 ![image](https://user-images.githubusercontent.com/63115449/135084777-870b9a88-de75-4079-9fe0-bc882945bedb.png)

1.  마우스 오버시 나타나는 정보의 시인성이 좋지 못함(같이 흐려짐)
2. 상단부분 여백 추가하여 시인성 확보
3. 하단부분 사이즈 맞지않는 부분 수정 필요

# 즐겨찾기

![image](https://user-images.githubusercontent.com/63115449/135086618-a139e0ef-c226-4aaa-8ab5-f1fd7bde375d.png)

1. 현재의 1/3 크기로 조정
2. 마우스 오버시 현재 사이즈로
3. 마우스 오버시 타이틀 표출

# 전체 레이아웃

![image](https://user-images.githubusercontent.com/63115449/135086834-77821963-d74e-43ee-9045-52e76530434c.png)

1. 메인 컨텐츠가 중앙에 오도록
(현재는 즐겨찾기때문에 우측으로 이동되어있음)

2021-09-29 04:00 UTC, itsChrisJang commented
확인했습니다 !!  해당 내용 토대로 진행할게요

2021-10-01 01:28 UTC, develjsh approved these changes, later dismissed
확인했습니다

2021-10-01 04:26 UTC, dntjr031 commented
> 확인했습니다 !! 해당 내용 토대로 진행할게요

진행하면서 궁금하거나 어려운 부분, 잘 안되는 부분 있으면 언제든 질문해주세요!

2021-10-09 07:39 UTC, itsChrisJang commented
eact-tooltip package.json 추가
포스터
1. 마우스 오버시 나타나는 정보의 시인성이 좋지 못함(같이 흐려짐)
=> 정보 포스터 위로 올림
2. 상단부분 여백 추가하여 시인성 확보
=> 전체적으로 크기 수정하였음
3. 하단부분 사이즈 맞지않는 부분 수정 필요
=> 수정/ 웹크기 바뀔때 이미지 크기 고정되게 바꿈
즐겨찾기
1. 현재의 1/3 크기로 조정
=> 완료
2. 마우스 오버시 현재 사이즈로
=> 완료
3. 마우스 오버시 타이틀 표출
전체 레이아웃
=> react tooltip 사용하여 구현함.
1. 메인 컨텐츠가 중앙에 오도록
(현재는 즐겨찾기때문에 우측으로 이동되어있음
=> 완료

2021-10-09 12:35 UTC, JAEMIN-LEE-ANDREW approved these changes
깔꿈 하네요

2021-10-09 13:46 UTC, develjsh approved these changes
확인했습니다

2021-10-12 04:11 UTC, dntjr031 approved these changes

2025-04-16 08:43 UTC, merged